// SignatoriesList.jsx

const signatories = [
  "21-87",
  "216 Signs",
  "31% Wool",
  "400",
  "A-Side.",
  "Aalia Ahmed",
  "Abbie Williams",
  "Abigail Brough",
  "Abigail C. Smith",
  "Abigail Dean",
  "Abigail Gibbons",
  "Abigail O’Brien",
  "Abigail Pavey",
  "Abigail Watson",
  "Abolore Shobayo",
  "Abraham Adeyemi",
  "Adam Bennett",
  "Adam Broomberg",
  "Adam Farah",
  "Adam Frost",
  "Adam Hines-Green",
  "Adam Moore",
  "Adam Murray",
  "Adam Nathaniel Furman",
  "Adam Pugh",
  "Adam Quinn",
  "Adam Sadiq",
  "Adam Sutherland",
  "Adam Tuck",
  "Adam Walker",
  "Adam White",
  "Adela Mede",
  "Adele Mary Reed",
  "Adeola Olagunju",
  "Adham Faramawy",
  "Adi Nes",
  "Aditya Mandayam",
  "Adjoa Armah",
  "Adrian Burnham",
  "Adrian Lee",
  "Adrian Paci",
  "Adrian Piper",
  "Adrian Shaw",
  "Adrienne Adar",
  "Adrienne Brown",
  "Adrienne Francis",
  "Adrienne Samos",
  "Afra Eisma",
  "Afshan D’souza-Lodhi",
  "Agata Madejska",
  "Agata Pyzik",
  "Agata Wieczorek",
  "Agathe Snow",
  "Aggie Toppins",
  "Agnes Cameron",
  "Agnes Denes",
  "Agnes Meyer-Brandis",
  "Agnes Nedregard",
  "Agnes Varda",
  "Agnieszka Kurant",
  "Agnieszka Polska",
  "Agustin Fernandez Mallo",
  "Agustin Perez Rubio",
  "Agustin Schang",
  "Ahmad Hosseini",
  "Ahmad Saleh",
  "Ahmed Al-Nawas",
  "Ahmed Mater",
  "Ahmed Shihab-Eldin",
  "Aida Muluneh",
  "Aidan Moesby",
  "Aidan O’Neill",
  "Aidan Saunders",
  "Aidan Synnott",
  "Aidan Turner",
  "Aidan Wallace",
  "Aideen Barry",
  "Ailbhe Ní Bhriain",
  "Ailsa Cavers",
  "Aimee Parrott",
  "Aimee Shapiro",
  "Aimee Zito Lema",
  "Aine O’Brien",
  "Aine Phillips",
  "Ainhoa Montoya",
  "Ainslie Henderson",
  "Aiofe O’Dwyer",
  "Airyka Rockefeller",
  "Aisha Abid Hussain",
  "Aisha Mirza",
  "Aisha Orazbayeva",
  "Aisha S. Khalid",
  "Aisling O’Beirn",
  "Aisling O’Rourke",
  "Aisling Ryan",
  "Aitor Lajarin",
  "Aitor Throup",
  "Aivars Vilipsons",
  "Aiyesha Siddiqi",
  "Ajamu X",
  "Akash Bhatt",
  "Akash Shergill",
  "Akemi Takeya",
  "Akiko Ichikawa",
  "Akiko Sato",
  "Akil Ahamat",
  "Akil Scafe-Smith",
  "Akilah Watts",
  "Akilina Tsonkova",
  "Akira Akira",
  "Akira Kurosawa",
  "Akira Rabelais",
  "Akram Zaatari",
  "Akshaya Sawant",
  "Alaa Abu Asad",
  "Alaa Edris",
  "Alaa Satir",
  "Alan Butler",
  "Alan Dunn",
  "Alan Kane",
  "Alan Magee",
  "Alan Michael",
  "Alan Phelan",
  "Alan Saret",
  "Alan Stivell",
  "Alan Warburton",
  "Alana Lake",
  "Alana O’Neill",
  "Alanna Lawley",
  "Alannah Robins",
  "Alastair Levy",
  "Alastair MacKinven",
  "Alastair Noble",
  "Alastair Sooke",
  "Alastair Thain",
  "Alastair White",
  "Alba D’Urbano",
  "Alba Lorente",
  "Alba Sotorra",
  "Alban Hajdinaj",
  "Alban Muja",
  "Alban O’Brien",
  "Albano Afonso",
  "Albert Allgaier",
  "Albert Baronian",
  "Albert Bertelsen",
  "Albert Camus",
  "Albert Coers",
  "Albert Dada",
  "Albert Heta",
  "Albert Irvin",
  "Albert Oehlen",
  "Albert Serra",
  "Albert Watson",
  "Alberta Whittle",
  "Alberto Baraya",
  "Alberto Biasi",
  "Alberto Burri",
  "Alberto De Michele",
  "Alberto Di Fabio",
  "Alberto Garutti",
  "Alberto Giacometti",
  "Alberto Grifi",
  "Alberto Laiseca",
  "Alberto Magnelli",
  "Alberto Sorbelli",
  "Alberto Tadiello",
  "Alberto Toscano",
  "Alberto Vettori",
  "Albina Akhatova",
  "Albina Fedorova",
  "Albina Shagimuratova",
  "Albino Luciani",
  "Albrecht Dürer",
  "Albrecht Schnider",
  "Alby Bailey",
  "Alceo Dossena",
  "Alceu Valença",
  "Alda Merini",
  "Aldo Braibanti",
  "Aldo Mondino",
  "Aldo Tambellini",
  "Alec Finlay",
  "Alec Soth",
  "Alecia Neo",
  "Alecus Talamantez",
  "Alejandra Alarcon",
  "Alejandra Atarés",
  "Alejandra Carles-Tolra",
  "Alejandra Ghersi",
  "Alejandra Laviada",
  "Alejandra Prieto",
  "Alejandra Seeber",
  "Alejandra Uslenghi",
  "Alejandro Almanza Pereda",
  "Alejandro Cesarco",
  "Alejandro Chaskielberg",
  "Alejandro González Iñárritu",
  "Alejandro Jodorowsky",
  "Alejandro Magallanes",
  "Alejandro Paz",
  "Alejandro Ramírez",
  "Alejandro Tantanian",
  "Alejandro Thornton",
  "Alejandro Vaca",
  "Aleksandar Duravcevic",
  "Aleksandar Hemon",
  "Aleksandar Todorovic",
  "Aleksandra Domanovic",
  "Aleksandra Mir",
  "Aleksandra Waliszewska",
  "Aleksandras Macijauskas",
  "Aleksandrs Petukhovs",
  "Aleksis Kivi",
  "Aleksei Kruchenykh",
  "Aleksei Navalny",
  "Aleksei Yeliseyev",
  "Aleksey Buldakov",
  "Aleksey Gastev",
  "Aleksey Kallima",
  "Aleksey Kiselev",
  "Aleksey Kondratyev",
  "Aleksey Krupnyakov",
  "Aleksey Larin",
  "Aleksey Leonov",
  "Aleksey Orlovsky",
  "Aleksey Parygin",
  "Aleksey Potekhin",
  "Aleksey Savrasov",
  "Aleksey Shchusev",
  "Aleksey Titarenko",
  "Aleksey Vasiliev",
  "Aleksey Yorsh",
  "Alessandra Ferrini",
  "Alessandra Spranzi",
  "Alessia Armeni",
  "Alessia Rollo",
  "Alessio Bolzoni",
  "Alessio Deli",
  "Alessio Forgione",
  "Alessio Mamo",
  "Alessio Romenzi",
  "Aletta Ocean",
  "Alex Ayed",
  "Alex Baczynski-Jenkins",
  "Alex Baker",
  "Alex Ball",
  "Alex Bate",
  "Alex Bennett",
  "Alex Bishop-Thorpe",
  "Alex Blackmore",
  "Alex Bloor",
  "Alex Box",
  "Alex Braden",
  "Alex Brown",
  "Alex Cecchetti",
  "Alex Chinneck",
  "Alex Clarke",
  "Alex Cline",
  "Alex Colard",
  "Alex Cook",
  "Alex Da Corte",
  "Alex Davies",
  "Alex De Corte",
  "Alex De Mora",
  "Alex Dipple",
  "Alex Dodge",
  "Alex Dower",
  "Alex Edelman",
  "Alex Ekins",
  "Alex Evans",
  "Alex Flett",
  "Alex Frost",
  "Alex Galloway",
  "Alex Gardner",
  "Alex Gawronski",
  "Alex Gene Morrison",
  "Alex Gibbs",
  "Alex Goodman",
  "Alex Green",
  "Alex Hackett",
  "Alex Hamilton",
  "Alex Hartley",
  "Alex Head",
  "Alex Hetherington",
  "Alex Higham",
  "Alex Hoda",
  "Alex Hudson",
  "Alex Israel",
  "Alex J. Gardner",
  "Alex Jackson",
  "Alex Jeffrey",
  "Alex Johnson",
  "Alex Katz",
  "Alex Kay",
  "Alex Kellner",
  "Alex Kerr",
  "Alex Kershaw",
  "Alex Kilgore",
  "Alex Klein",
  "Alex Knost",
  "Alex Kroll",
  "Alex Landrum",
  "Alex Law",
  "Alex Leese",
  "Alex Leith",
  "Alex Lewis",
  "Alex Lockwood",
  "Alex Margo Arden",
  "Alex Martinis Roe",
  "Alex Massouras",
  "Alex Mayhew",
  "Alex McNamee",
  "Alex Meade",
  "Alex Mirutziu",
  "Alex Morrison",
  "Alex Moulton",
  "Alex Nagle",
  "Alex Niven",
  "Alex Norris",
  "Alex O’Neill",
  "Alex P. White",
  "Alex Pearl",
  "Alex Penfold",
  "Alex Perry",
  "Alex Pfaff",
  "Alex Pichler",
  "Alex Prager",
  "Alex Price",
  "Alex Quicho",
  "Alex Ressel",
  "Alex Rich",
  "Alex Rigg",
  "Alex Roberts",
  "Alex Ross",
  "Alex Rowbotham",
  "Alex Rutterford",
  "Alex Sainsbury",
  "Alex Schady",
  "Alex Schweder",
  "Alex Scrivener",
  "Alex Shepherd",
  "Alex Simpson",
  "Alex Sloley",
  "Alex Smith",
  "Alex South",
  "Alex Sturrock",
  "Alex Sutherland",
  "Alex Taylor",
  "Alex Telfer",
  "Alex Tennant",
  "Alex Thornton",
  "Alex Tingle",
  "Alex Toth",
  "Alex Turner",
  "Alex Urso",
  "Alex Valentine",
  "Alex Vardaxoglou",
  "Alex Varenne",
  "Alex Vass",
  "Alex Veness",
  "Alex Verhaest",
  "Alex Webb",
  "Alex Weir",
  "Alex Whittaker",
  "Alex Williams",
  "Alex Wilson",
  "Alex Wood",
  "Alex Wright",
  "Alex Young",
  "Alexa Becker",
  "Alexa Karolinski",
  "Alexa Wright",
  "Alexander Apostol",
  "Alexander Archipenko",
  "Alexander Basile",
  "Alexander Bickov",
  "Alexander Brodsky",
  "Alexander Calder",
  "Alexander Chekmenev",
  "Alexander Coggin",
  "Alexander Cozens",
  "Alexander Donskoi",
  "Alexander Ekman",
  "Alexander Gorlizki",
  "Alexander Gronsky",
  "Alexander Hamilton",
  "Alexander James",
  "Alexander Kluge",
  "Alexander Korzer-Robinson",
  "Alexander Kotsis",
  "Alexander Krivosheiw",
  "Alexander Kroll",
  "Alexander Laner",
  "Alexander Liebreich",
  "Alexander McQueen",
  "Alexander Mihaylovich",
  "Alexander Molodkin",
  "Alexander Nemerov",
  "Alexander O’Neal",
  "Alexander Pilis",
  "Alexander Polzin",
  "Alexander Povzner",
  "Alexander Reben",
  "Alexander Rodchenko",
  "Alexander Sokurov",
  "Alexander Stoddart",
  "Alexander Tinei",
  "Alexander Tovborg",
  "Alexander Ugay",
  "Alexander Vantournhout",
  "Alexander Wagner",
  "Alexander Wolfe",
  "Alexander Yulish",
  "Alexandra Bachzetsis",
  "Alexandra Bell",
  "Alexandra Bircken",
  "Alexandra Bisbicus",
  "Alexandra Daisy Ginsberg",
  "Alexandra Domanovic",
  "Alexandra Exter",
  "Alexandra Grant",
  "Alexandra Hopf",
  "Alexandra Karpova",
  "Alexandra Lerman",
  "Alexandra Leykauf",
  "Alexandra Marzella",
  "Alexandra Mir",
  "Alexandra Navratil",
  "Alexandra Pirici",
  "Alexandra Sukhareva",
  "Alexandra Zsigmond",
  "Alexandros Georgiou",
  "Alexandros Tzannis",
  "Alexei Blinov",
  "Alexei Lubimov",
  "Alexei Shulgin",
  "Alexej Koschkarow",
  "Alexey Bogolepov",
  "Alexey Kallima",
  "Alexey Kiselev",
  "Alexey Kondratyev",
  "Alexey Krupnyakov",
  "Alexey Larin",
  "Alexey Orlovsky",
  "Alexey Parygin",
  "Alexey Potekhin",
  "Alexey Savrasov",
  "Alexey Shchusev",
  "Alexey Titarenko",
  "Alexey Vasiliev",
  "Alexey Yorsh"
];

export default function SignatoriesList() {
  return (
    <div className="bg-black text-white min-h-screen p-8">
      <h1 className="text-5xl font-bold mb-2">#514</h1>
      <h2 className="text-2xl mb-8">
        Signatories and counting in{" "}
        <span className="bg-orange-600 text-white text-base rounded-full px-3 py-1 inline-block">
          D!UK
        </span>
      </h2>

      <div className="grid grid-cols-3 sm:grid-cols-5 md:grid-cols-7 lg:grid-cols-9 gap-2 text-xs tracking-tight leading-tight">
        {signatories.map((name, idx) => (
          <a
  key={idx}
  href="https://www.pentagram.com/"
  target="_blank"
  rel="noopener noreferrer"
  className="hover:underline transition-all px-1 py-0.5"
>
  {name}
  </a>
        ))}
      </div>
    </div>
  );
}

